"""
Visualize tournament game logs from JSON files generated by `agentVSagent.py` or `run_agent_tournament.py`.

Usage: python3 src/chess/visualizer.py <path_to_log_json>
"""

import os
import sys
import json
import argparse
import pyffish
from bottle import route, run, template, response, static_file
from src.utils.utils import get_svg_board

# Gardner start FEN
START_FEN = "rnbqk/ppppp/5/PPPPP/RNBQK w - - 0 1"

def load_log(log_path):
    if not os.path.exists(log_path):
        print(f"[ERROR] Log file {log_path} not found.")
        sys.exit(1)
    with open(log_path, "r") as f:
        return json.load(f)

# Global variables to store log data
LOG_DATA = None
GAMES = []

@route('/')
def index():
    return static_file("gameVisualizer.html", root="src/chess")

@route('/api/games')
def get_games():
    response.content_type = 'application/json'
    summary = LOG_DATA.get("summary", {})
    return json.dumps({
        "agent1": LOG_DATA.get("agent1", {}),
        "agent2": LOG_DATA.get("agent2", {}),
        "summary": summary,
        "games": [
            {
                "game_idx": g["game_idx"],
                "white": g["white"],
                "black": g["black"],
                "winner": g["winner"],
                "reason": g["reason"],
                "num_moves": g["num_moves"]
            } for g in GAMES
        ]
    })

@route('/api/game/<game_idx:int>/move/<move_idx:int>')
def get_move_state(game_idx, move_idx):
    response.content_type = 'application/json'
    if game_idx < 1 or game_idx > len(GAMES):
        return json.dumps({"error": "Invalid game index"})
    
    game = GAMES[game_idx - 1]
    moves = game["moves"]
    
    if move_idx < 0 or move_idx > len(moves):
        return json.dumps({"error": "Invalid move index"})
    
    # Initialize pyffish
    pyffish.set_option("UCI_Variant", "gardner")
    
    # Reconstruct move list up to move_idx
    # In the JSON, moves can be list of dicts (new format) or list of strings (old format).
    move_strings = []
    for m in moves[:move_idx]:
        if isinstance(m, dict):
            move_strings.append(m["move"])
        else:
            move_strings.append(m)
            
    current_fen = pyffish.get_fen("gardner", START_FEN, move_strings)
    
    # Render SVG board
    board_inner = get_svg_board(current_fen)
    sq = 60
    width, height = 5 * sq, 5 * sq
    board_svg = f'<svg width="100%" height="100%" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">{board_inner}</svg>'
    
    # Current move info
    if move_idx == 0:
        played_move = None
        played_by = None
    else:
        last_move = moves[move_idx - 1]
        if isinstance(last_move, dict):
            played_move = last_move["move"]
            played_by = last_move["player"]
        else:
            played_move = last_move
            played_by = "white" if (move_idx - 1) % 2 == 0 else "black"
        
    # The next move is predicted at the current FEN.
    if move_idx < len(moves):
        next_move = moves[move_idx]
        if isinstance(next_move, dict):
            entropy = next_move.get("entropy", 0.0)
            top_6 = next_move.get("top_6", [])
            active_player = next_move.get("player", "white")
        else:
            entropy = 0.0
            top_6 = []
            active_player = "white" if move_idx % 2 == 0 else "black"
    else:
        entropy = 0.0
        top_6 = []
        parts = current_fen.split(" ")
        active_player = "white" if parts[1] == "w" else "black"
        
    return json.dumps({
        "fen": current_fen,
        "board_svg": board_svg,
        "played_move": played_move,
        "played_by": played_by,
        "active_player": active_player,
        "entropy": entropy,
        "top_6": top_6,
        "move_idx": move_idx,
        "num_moves": len(moves)
    })

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Start the Minichess tournament log visualizer")
    parser.add_argument("log_path", type=str, help="Path to the tournament log JSON file")
    parser.add_argument("--port", type=int, default=8080, help="Port to run the visualizer server on")
    parser.add_argument("--host", type=str, default="127.0.0.1", help="Host address to run visualizer server on")
    
    args = parser.parse_args()
    
    # Load game logs
    LOG_DATA = load_log(args.log_path)
    GAMES = LOG_DATA.get("games", [])
    
    print(f"[*] Visualizer loaded: {len(GAMES)} games from {args.log_path}")
    print(f"[*] Open http://{args.host}:{args.port}/ in your web browser to view the visualizer.")
    
    run(host=args.host, port=args.port)
